// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sidwell.Core.Infrastructure.Data;

#nullable disable

namespace Sidwell.Core.Infrastructure.Migrations
{
    [DbContext(typeof(SidwellDbContext))]
    [Migration("20260726101100_AddNewsSourceAndTxPriceAuto")]
    partial class AddNewsSourceAndTxPriceAuto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sidwell.Core.Domain.Entities.Algorithm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPhilosophyDependent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_philosophy_dependent");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_algorithms");

                    b.HasIndex("Name", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_algorithms_name_version");

                    b.ToTable("algorithms", (string)null);
                });

            modelBuilder.Entity("Sidwell.Core.Domain.Entities.AlgorithmScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AlgorithmId")
                        .HasColumnType("uuid")
                        .HasColumnName("algorithm_id");

                    b.Property<DateOnly>("AsOfDate")
                        .HasColumnType("date")
                        .HasColumnName("as_of_date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Details")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("details")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("Philosophy")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("philosophy");

                    b.Property<decimal?>("Score")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("score");

                    b.Property<Guid>("TickerId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticker_id");

                    b.HasKey("Id")
                        .HasName("pk_algorithm_scores");

                    b.HasIndex("AlgorithmId")
                        .HasDatabaseName("ix_algorithm_scores_algorithm_id");

                    b.HasIndex("TickerId")
                        .HasDatabaseName("ix_algorithm_scores_ticker_id");

                    b.HasIndex("TickerId", "AlgorithmId", "Philosophy", "AsOfDate")
                        .IsUnique()
                        .HasDatabaseName("ix_algorithm_scores_ticker_id_algorithm_id_philosophy_as_of_da");

                    b.ToTable("algorithm_scores", null, t =>
                        {
                            t.HasCheckConstraint("ck_algorithm_scores_philosophy", "philosophy IN ('ALL', 'BALANCED', 'MOMENTUM', 'MEAN_REVERSION', 'FUNDAMENTAL')");
                        });
                });

            modelBuilder.Entity("Sidwell.Core.Domain.Entities.ApiCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("EncryptedKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("encrypted_key");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("provider");

                    b.Property<DateTimeOffset>("RotatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rotated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_api_credentials");

                    b.HasIndex("Provider")
                        .IsUnique()
                        .HasDatabaseName("ix_api_credentials_provider");

                    b.ToTable("api_credentials", (string)null);
                });

            modelBuilder.Entity("Sidwell.Core.Domain.Entities.BrokerFeeSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Broker")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("broker");

                    b.Property<string>("Currency")
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal?>("FixedFee")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("fixed_fee");

                    b.Property<string>("Market")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("market");

                    b.Property<decimal?>("MinFee")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("min_fee");

                    b.Property<decimal?>("Percent")
                        .HasPrecision(10, 6)
                        .HasColumnType("numeric(10,6)")
                        .HasColumnName("percent");

                    b.Property<string>("Raw")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("source_url");

                    b.HasKey("Id")
                        .HasName("pk_broker_fee_schedules");

                    b.HasIndex("Broker", "Market")
                        .IsUnique()
                        .HasDatabaseName("ix_broker_fee_schedules_broker_market");

                    b.ToTable("broker_fee_schedules", null, t =>
                        {
                            t.HasCheckConstraint("ck_broker_fee_schedules_broker", "broker IN ('TRADEVILLE', 'XTB', 'IBKR')");
                        });
                });

            modelBuilder.Entity("Sidwell.Core.Domain.Entities.DividendTaxRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .HasColumnName("country_code");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<decimal>("RatePercent")
                        .HasPrecision(10, 6)
                        .HasColumnType("numeric(10,6)")
                        .HasColumnName("rate_percent");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("source_url");

                    b.HasKey("Id")
                        .HasName("pk_dividend_tax_rates");

                    b.HasIndex("CountryCode")
                        .IsUnique()
                        .HasDatabaseName("ix_dividend_tax_rates_country_code");

                    b.ToTable("dividend_tax_rates", (string)null);
                });

            modelBuilder.Entity("Sidwell.Core.Domain.Entities.ExchangeRate", b =>
                {
                    b.Property<string>("Currency")
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<DateOnly>("RateDate")
                        .HasColumnType("date")
                        .HasColumnName("rate_date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("RateToRon")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("rate_to_ron");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("source");

                    b.HasKey("Currency", "RateDate")
                        .HasName("pk_exchange_rates");

                    b.HasIndex("Currency", "RateDate")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_exchange_rates_currency_date_desc");

                    b.ToTable("exchange_rates", (string)null);
                });

            modelBuilder.Entity("Sidwell.Core.Domain.Entities.Fundamental", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal?>("AccountsReceivable")
                        .HasPrecision(20, 2)
                        .HasColumnType("numeric(20,2)")
                        .HasColumnName("accounts_receivable");

                    b.Property<DateOnly>("AsOfDate")
                        .HasColumnType("date")
                        .HasColumnName("as_of_date");

                    b.Property<decimal?>("BookValuePerShare")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("book_value_per_share");

                    b.Property<decimal?>("Capex")
                        .HasPrecision(20, 2)
                        .HasColumnType("numeric(20,2)")
                        .HasColumnName("capex");

                    b.Property<decimal?>("Cash")
                        .HasPrecision(20, 2)
                        .HasColumnType("numeric(20,2)")
                        .HasColumnName("cash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal?>("CurrentAssets")
                        .HasPrecision(20, 2)
                        .HasColumnType("numeric(20,2)")
                        .HasColumnName("current_assets");

                    b.Property<decimal?>("CurrentLiabilities")
                        .HasPrecision(20, 2)
                        .HasColumnType("numeric(20,2)")
                        .HasColumnName("current_liabilities");

                    b.Property<decimal?>("Depreciation")
                        .HasPrecision(20, 2)
                        .HasColumnType("numeric(20,2)")
                        .HasColumnName("depreciation");

                    b.Property<decimal?>("DividendGrowth")
                        .HasPrecision(10, 6)
                        .HasColumnType("numeric(10,6)")
                        .HasColumnName("dividend_growth");

                    b.Property<decimal?>("DividendPerShare")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("dividend_per_share");

                    b.Property<decimal?>("DividendYield")
                        .HasPrecision(10, 6)
                        .HasColumnType("numeric(10,6)")
                        .HasColumnName("dividend_yield");

                    b.Property<decimal?>("Ebit")
                        .HasPrecision(20, 2)
                        .HasColumnType("numeric(20,2)")
                        .HasColumnName("ebit");

                    b.Property<decimal?>("Ebitda")
                        .HasPrecision(20, 2)
                        .HasColumnType("numeric(20,2)")
                        .HasColumnName("ebitda");

                    b.Property<decimal?>("Eps")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("eps");

                    b.Property<decimal?>("FreeCashFlow")
                        .HasPrecision(20, 2)
                        .HasColumnType("numeric(20,2)")
                        .HasColumnName("free_cash_flow");

                    b.Property<decimal?>("GrossProfit")
                        .HasPrecision(20, 2)
                        .HasColumnType("numeric(20,2)")
                        .HasColumnName("gross_profit");

                    b.Property<decimal?>("LongTermDebt")
                        .HasPrecision(20, 2)
                        .HasColumnType("numeric(20,2)")
                        .HasColumnName("long_term_debt");

                    b.Property<decimal?>("MarketCap")
                        .HasPrecision(24, 2)
                        .HasColumnType("numeric(24,2)")
                        .HasColumnName("market_cap");

                    b.Property<decimal?>("NetIncome")
                        .HasPrecision(20, 2)
                        .HasColumnType("numeric(20,2)")
                        .HasColumnName("net_income");

                    b.Property<decimal?>("OperatingCashFlow")
                        .HasPrecision(20, 2)
                        .HasColumnType("numeric(20,2)")
                        .HasColumnName("operating_cash_flow");

                    b.Property<decimal?>("PeRatio")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("pe_ratio");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("period");

                    b.Property<decimal?>("PpeNet")
                        .HasPrecision(20, 2)
                        .HasColumnType("numeric(20,2)")
                        .HasColumnName("ppe_net");

                    b.Property<string>("Raw")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<decimal?>("RetainedEarnings")
                        .HasPrecision(20, 2)
                        .HasColumnType("numeric(20,2)")
                        .HasColumnName("retained_earnings");

                    b.Property<decimal?>("Revenue")
                        .HasPrecision(20, 2)
                        .HasColumnType("numeric(20,2)")
                        .HasColumnName("revenue");

                    b.Property<decimal?>("Roe")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("roe");

                    b.Property<decimal?>("SgaExpense")
                        .HasPrecision(20, 2)
                        .HasColumnType("numeric(20,2)")
                        .HasColumnName("sga_expense");

                    b.Property<long?>("SharesOutstanding")
                        .HasColumnType("bigint")
                        .HasColumnName("shares_outstanding");

                    b.Property<Guid>("TickerId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticker_id");

                    b.Property<decimal?>("TotalAssets")
                        .HasPrecision(20, 2)
                        .HasColumnType("numeric(20,2)")
                        .HasColumnName("total_assets");

                    b.Property<decimal?>("TotalDebt")
                        .HasPrecision(20, 2)
                        .HasColumnType("numeric(20,2)")
                        .HasColumnName("total_debt");

                    b.Property<decimal?>("TotalEquity")
                        .HasPrecision(20, 2)
                        .HasColumnType("numeric(20,2)")
                        .HasColumnName("total_equity");

                    b.Property<decimal?>("TotalLiabilities")
                        .HasPrecision(20, 2)
                        .HasColumnType("numeric(20,2)")
                        .HasColumnName("total_liabilities");

                    b.HasKey("Id")
                        .HasName("pk_fundamentals");

                    b.HasIndex("TickerId")
                        .HasDatabaseName("ix_fundamentals_ticker_id");

                    b.HasIndex("TickerId", "AsOfDate", "Period")
                        .IsUnique()
                        .HasDatabaseName("ix_fundamentals_ticker_id_as_of_date_period");

                    b.ToTable("fundamentals", (string)null);
                });

            modelBuilder.Entity("Sidwell.Core.Domain.Entities.Holding", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("TickerId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticker_id");

                    b.Property<decimal>("AvgCost")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasDefaultValue(0m)
                        .HasColumnName("avg_cost");

                    b.Property<decimal>("RealizedPnl")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(20, 6)
                        .HasColumnType("numeric(20,6)")
                        .HasDefaultValue(0m)
                        .HasColumnName("realized_pnl");

                    b.Property<decimal>("Shares")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasDefaultValue(0m)
                        .HasColumnName("shares");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("UserId", "TickerId")
                        .HasName("pk_holdings");

                    b.HasIndex("TickerId")
                        .HasDatabaseName("ix_holdings_ticker_id");

                    b.ToTable("holdings", (string)null);
                });

            modelBuilder.Entity("Sidwell.Core.Domain.Entities.InsiderTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Insider")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("insider");

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("price");

                    b.Property<decimal>("Shares")
                        .HasPrecision(20, 4)
                        .HasColumnType("numeric(20,4)")
                        .HasColumnName("shares");

                    b.Property<Guid>("TickerId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticker_id");

                    b.Property<DateOnly>("TxDate")
                        .HasColumnType("date")
                        .HasColumnName("tx_date");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_insider_transactions");

                    b.HasIndex("TickerId", "TxDate")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_insider_transactions_ticker_tx_date");

                    b.ToTable("insider_transactions", (string)null);
                });

            modelBuilder.Entity("Sidwell.Core.Domain.Entities.NewsItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<decimal?>("Sentiment")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("sentiment");

                    b.Property<string>("Source")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source");

                    b.Property<Guid>("TickerId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticker_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_news_items");

                    b.HasIndex("Url")
                        .IsUnique()
                        .HasDatabaseName("ix_news_items_url");

                    b.HasIndex("TickerId", "PublishedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_news_items_ticker_published");

                    b.ToTable("news_items", (string)null);
                });

            modelBuilder.Entity("Sidwell.Core.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Body")
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_notifications_user_unread")
                        .HasFilter("is_read = false");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_notifications_user_created");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("Sidwell.Core.Domain.Entities.PortfolioTarget", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("TickerId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticker_id");

                    b.Property<decimal>("TargetShares")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("target_shares");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("UserId", "TickerId")
                        .HasName("pk_portfolio_targets");

                    b.HasIndex("TickerId")
                        .HasDatabaseName("ix_portfolio_targets_ticker_id");

                    b.ToTable("portfolio_targets", null, t =>
                        {
                            t.HasCheckConstraint("ck_portfolio_targets_target_shares", "target_shares >= 0");
                        });
                });

            modelBuilder.Entity("Sidwell.Core.Domain.Entities.PriceHistory", b =>
                {
                    b.Property<Guid>("TickerId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticker_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<decimal>("Close")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("close");

                    b.Property<decimal>("High")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("high");

                    b.Property<decimal>("Low")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("low");

                    b.Property<decimal>("Open")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("open");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("source");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint")
                        .HasColumnName("volume");

                    b.HasKey("TickerId", "Date")
                        .HasName("pk_price_history");

                    b.HasIndex("TickerId", "Date")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_price_history_ticker_date_desc");

                    b.ToTable("price_history", (string)null);
                });

            modelBuilder.Entity("Sidwell.Core.Domain.Entities.ScreenerPreset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Criteria")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("criteria")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_screener_presets");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_screener_presets_user_id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_screener_presets_user_id_name");

                    b.ToTable("screener_presets", (string)null);
                });

            modelBuilder.Entity("Sidwell.Core.Domain.Entities.SecFiling", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AccessionNo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("accession_no");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly>("FilingDate")
                        .HasColumnType("date")
                        .HasColumnName("filing_date");

                    b.Property<string>("FormType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("form_type");

                    b.Property<Guid>("TickerId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticker_id");

                    b.HasKey("Id")
                        .HasName("pk_sec_filings");

                    b.HasIndex("AccessionNo")
                        .IsUnique()
                        .HasDatabaseName("ix_sec_filings_accession_no");

                    b.HasIndex("TickerId", "FilingDate")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_sec_filings_ticker_filing_date");

                    b.ToTable("sec_filings", (string)null);
                });

            modelBuilder.Entity("Sidwell.Core.Domain.Entities.SyncJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_sync_jobs");

                    b.HasIndex("Source", "StartedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_sync_jobs_source_started");

                    b.ToTable("sync_jobs", null, t =>
                        {
                            t.HasCheckConstraint("ck_sync_jobs_status", "status IN ('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED')");
                        });
                });

            modelBuilder.Entity("Sidwell.Core.Domain.Entities.Ticker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("exchange");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("SecCik")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("sec_cik");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("symbol");

                    b.HasKey("Id")
                        .HasName("pk_tickers");

                    b.HasIndex("Symbol", "Exchange")
                        .IsUnique()
                        .HasDatabaseName("ix_tickers_symbol_exchange");

                    b.ToTable("tickers", (string)null);
                });

            modelBuilder.Entity("Sidwell.Core.Domain.Entities.TickerDividend", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal?>("DividendYield")
                        .HasPrecision(10, 6)
                        .HasColumnType("numeric(10,6)")
                        .HasColumnName("dividend_yield");

                    b.Property<DateOnly?>("ExDividendDate")
                        .HasColumnType("date")
                        .HasColumnName("ex_dividend_date");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal?>("ForwardDividend")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("forward_dividend");

                    b.Property<decimal?>("HistGrowthCagr")
                        .HasPrecision(10, 6)
                        .HasColumnType("numeric(10,6)")
                        .HasColumnName("hist_growth_cagr");

                    b.Property<string>("PayFrequency")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("pay_frequency");

                    b.Property<string>("Raw")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("source_url");

                    b.Property<Guid>("TickerId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticker_id");

                    b.HasKey("Id")
                        .HasName("pk_ticker_dividends");

                    b.HasIndex("TickerId")
                        .IsUnique()
                        .HasDatabaseName("ix_ticker_dividends_ticker_id");

                    b.ToTable("ticker_dividends", null, t =>
                        {
                            t.HasCheckConstraint("ck_ticker_dividends_pay_frequency", "pay_frequency IS NULL OR pay_frequency IN ('MONTHLY', 'QUARTERLY', 'SEMI_ANNUAL', 'ANNUAL', 'IRREGULAR')");
                        });
                });

            modelBuilder.Entity("Sidwell.Core.Domain.Entities.TickerNote", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("TickerId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticker_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("UserId", "TickerId")
                        .HasName("pk_ticker_notes");

                    b.HasIndex("TickerId")
                        .HasDatabaseName("ix_ticker_notes_ticker_id");

                    b.ToTable("ticker_notes", (string)null);
                });

            modelBuilder.Entity("Sidwell.Core.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("ExecutedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executed_at");

                    b.Property<decimal>("Fee")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasDefaultValue(0m)
                        .HasColumnName("fee");

                    b.Property<decimal?>("FxRateAtExecution")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("fx_rate_at_execution");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("price");

                    b.Property<bool>("PriceAuto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("price_auto");

                    b.Property<decimal>("Shares")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("shares");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("side");

                    b.Property<Guid>("TickerId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticker_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_transactions");

                    b.HasIndex("TickerId")
                        .HasDatabaseName("ix_transactions_ticker_id");

                    b.HasIndex("UserId", "ExecutedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_transactions_user_executed");

                    b.ToTable("transactions", null, t =>
                        {
                            t.HasCheckConstraint("ck_transactions_price", "price >= 0");

                            t.HasCheckConstraint("ck_transactions_shares", "shares > 0");

                            t.HasCheckConstraint("ck_transactions_side", "side IN ('BUY', 'SELL')");
                        });
                });

            modelBuilder.Entity("Sidwell.Core.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Sidwell.Core.Domain.Entities.UserSetting", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Key")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "Key")
                        .HasName("pk_user_settings");

                    b.ToTable("user_settings", (string)null);
                });

            modelBuilder.Entity("Sidwell.Core.Domain.Entities.WatchlistEntry", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("TickerId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticker_id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("UserId", "TickerId")
                        .HasName("pk_watchlist");

                    b.HasIndex("TickerId")
                        .HasDatabaseName("ix_watchlist_ticker_id");

                    b.ToTable("watchlist", (string)null);
                });

            modelBuilder.Entity("Sidwell.Core.Domain.Entities.WebauthnCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<byte[]>("CredentialId")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("credential_id");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("public_key");

                    b.Property<long>("SignCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("sign_count");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_webauthn_credentials");

                    b.HasIndex("CredentialId")
                        .IsUnique()
                        .HasDatabaseName("ix_webauthn_credentials_credential_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_webauthn_credentials_user_id");

                    b.ToTable("webauthn_credentials", (string)null);
                });

            modelBuilder.Entity("Sidwell.Core.Domain.Entities.AlgorithmScore", b =>
                {
                    b.HasOne("Sidwell.Core.Domain.Entities.Algorithm", null)
                        .WithMany()
                        .HasForeignKey("AlgorithmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_algorithm_scores_algorithms_algorithm_id");

                    b.HasOne("Sidwell.Core.Domain.Entities.Ticker", null)
                        .WithMany()
                        .HasForeignKey("TickerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_algorithm_scores_tickers_ticker_id");
                });

            modelBuilder.Entity("Sidwell.Core.Domain.Entities.Fundamental", b =>
                {
                    b.HasOne("Sidwell.Core.Domain.Entities.Ticker", null)
                        .WithMany()
                        .HasForeignKey("TickerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fundamentals_tickers_ticker_id");
                });

            modelBuilder.Entity("Sidwell.Core.Domain.Entities.Holding", b =>
                {
                    b.HasOne("Sidwell.Core.Domain.Entities.Ticker", null)
                        .WithMany()
                        .HasForeignKey("TickerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_holdings_tickers_ticker_id");

                    b.HasOne("Sidwell.Core.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_holdings_users_user_id");
                });

            modelBuilder.Entity("Sidwell.Core.Domain.Entities.InsiderTransaction", b =>
                {
                    b.HasOne("Sidwell.Core.Domain.Entities.Ticker", null)
                        .WithMany()
                        .HasForeignKey("TickerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_insider_transactions_tickers_ticker_id");
                });

            modelBuilder.Entity("Sidwell.Core.Domain.Entities.NewsItem", b =>
                {
                    b.HasOne("Sidwell.Core.Domain.Entities.Ticker", null)
                        .WithMany()
                        .HasForeignKey("TickerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_news_items_tickers_ticker_id");
                });

            modelBuilder.Entity("Sidwell.Core.Domain.Entities.Notification", b =>
                {
                    b.HasOne("Sidwell.Core.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_users_user_id");
                });

            modelBuilder.Entity("Sidwell.Core.Domain.Entities.PortfolioTarget", b =>
                {
                    b.HasOne("Sidwell.Core.Domain.Entities.Ticker", null)
                        .WithMany()
                        .HasForeignKey("TickerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_portfolio_targets_tickers_ticker_id");

                    b.HasOne("Sidwell.Core.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_portfolio_targets_users_user_id");
                });

            modelBuilder.Entity("Sidwell.Core.Domain.Entities.PriceHistory", b =>
                {
                    b.HasOne("Sidwell.Core.Domain.Entities.Ticker", null)
                        .WithMany()
                        .HasForeignKey("TickerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_price_history_tickers_ticker_id");
                });

            modelBuilder.Entity("Sidwell.Core.Domain.Entities.ScreenerPreset", b =>
                {
                    b.HasOne("Sidwell.Core.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_screener_presets_users_user_id");
                });

            modelBuilder.Entity("Sidwell.Core.Domain.Entities.SecFiling", b =>
                {
                    b.HasOne("Sidwell.Core.Domain.Entities.Ticker", null)
                        .WithMany()
                        .HasForeignKey("TickerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sec_filings_tickers_ticker_id");
                });

            modelBuilder.Entity("Sidwell.Core.Domain.Entities.TickerDividend", b =>
                {
                    b.HasOne("Sidwell.Core.Domain.Entities.Ticker", null)
                        .WithMany()
                        .HasForeignKey("TickerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticker_dividends_tickers_ticker_id");
                });

            modelBuilder.Entity("Sidwell.Core.Domain.Entities.TickerNote", b =>
                {
                    b.HasOne("Sidwell.Core.Domain.Entities.Ticker", null)
                        .WithMany()
                        .HasForeignKey("TickerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticker_notes_tickers_ticker_id");

                    b.HasOne("Sidwell.Core.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticker_notes_users_user_id");
                });

            modelBuilder.Entity("Sidwell.Core.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("Sidwell.Core.Domain.Entities.Ticker", null)
                        .WithMany()
                        .HasForeignKey("TickerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transactions_tickers_ticker_id");

                    b.HasOne("Sidwell.Core.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transactions_users_user_id");
                });

            modelBuilder.Entity("Sidwell.Core.Domain.Entities.UserSetting", b =>
                {
                    b.HasOne("Sidwell.Core.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_settings_users_user_id");
                });

            modelBuilder.Entity("Sidwell.Core.Domain.Entities.WatchlistEntry", b =>
                {
                    b.HasOne("Sidwell.Core.Domain.Entities.Ticker", null)
                        .WithMany()
                        .HasForeignKey("TickerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_watchlist_tickers_ticker_id");

                    b.HasOne("Sidwell.Core.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_watchlist_users_user_id");
                });

            modelBuilder.Entity("Sidwell.Core.Domain.Entities.WebauthnCredential", b =>
                {
                    b.HasOne("Sidwell.Core.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_webauthn_credentials_users_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
