// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Sidwell.Core.Infrastructure.Data;

namespace Sidwell.Core.Infrastructure.Migrations
{
    [DbContext(typeof(SidwellDbContext))]
    [Migration("20260814000001_DropAlgorithmsUseAlgoName")]
    partial class DropAlgorithmsUseAlgoName
    {
    }
}
